# Generated by Django 6.0.6 on 2026-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_department_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
