# Generated by Django 6.0.6 on 2026-07-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_department_student_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Department',
            new_name='Branch',
        ),
    ]
